In [4]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [6]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [13]:
arquivo = 'z0019_1.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao

df.head()

   NATBR     MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10    100    100  z0019_1.csv 2026-03-29 19:17:13.622547
1  10002   MARTELO  BT50    100   1500  z0019_1.csv 2026-03-29 19:17:13.622547
2  10003     PREGO  BT50    100     50  z0019_1.csv 2026-03-29 19:17:13.622547

In [19]:
con.execute('''
CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_arquivo VARCHAR,
        data_ingestao TIMESTAMP,

    )
''')

In [20]:
con.execute('''INSERT INTO bronze_produtos SELECT * FROM df''')

In [22]:
resultado = con.execute('SELECT * FROM bronze_produtos').fetchdf()
resultado.head()

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-03-29 19:17:13.622547
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-03-29 19:17:13.622547
2  10003     PREGO  BT50   100    50  z0019_1.csv 2026-03-29 19:17:13.622547

In [24]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao

df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-03-29 19:23:07.071167
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-03-29 19:23:07.071167
2  10003    PREGO  BT50    100     60  z0019_2.csv 2026-03-29 19:23:07.071167

In [25]:
con.execute('''INSERT INTO bronze_produtos SELECT * FROM df''')

In [28]:
resultado = con.execute('SELECT * FROM bronze_produtos').fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-03-29 19:17:13.622547
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-03-29 19:17:13.622547
2  10003     PREGO  BT50   100    50  z0019_1.csv 2026-03-29 19:17:13.622547
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-03-29 19:23:07.071167
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-03-29 19:23:07.071167
5  10003     PREGO  BT50   100    60  z0019_2.csv 2026-03-29 19:23:07.071167

In [7]:
con.execute('''ALTER TABLE z0019 RENAME TO bronze_z0019''')

In [ ]:
resultado = con.execute('SELECT * FROM bronze_z0019').fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-03-29 19:17:13.622547
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-03-29 19:17:13.622547
2  10003     PREGO  BT50   100    50  z0019_1.csv 2026-03-29 19:17:13.622547
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-03-29 19:23:07.071167
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-03-29 19:23:07.071167
5  10003     PREGO  BT50   100    60  z0019_2.csv 2026-03-29 19:23:07.071167

In [ ]:
con.close()