In [2]:
import duckdb

In [4]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [6]:
df = con.execute("SELECT * FROM produtos").fetchdf()
df.head(10)

      id      nome categoria  fornecedor   preco
0  10001  PARAFUSO      BT10         100   100.0
1  10002   MARTELO      BT50         100  1500.0
2  10004     SERRA      BT50         100   200.0
3  10005   MACHADO      BT50         100   100.0
4  10003     PREGO      BT50         100    60.0

In [10]:
df2 = df.drop(columns=['fornecedor', 'categoria'])
df2.head(10)

      id      nome   preco
0  10001  PARAFUSO   100.0
1  10002   MARTELO  1500.0
2  10004     SERRA   200.0
3  10005   MACHADO   100.0
4  10003     PREGO    60.0

In [11]:
con.execute("""CREATE TABLE IF NOT EXISTS dim_produtos (
        id BIGINT,
        nome VARCHAR,
        preco FLOAT
    )""")

In [16]:
con.execute("INSERT INTO dim_produtos SELECT * FROM df2")
df = con.execute("SELECT * FROM dim_produtos").fetchdf()
df.head(10)

      id      nome   preco
0  10001  PARAFUSO   100.0
1  10002   MARTELO  1500.0
2  10004     SERRA   200.0
3  10005   MACHADO   100.0
4  10003     PREGO    60.0
5  10001  PARAFUSO   100.0
6  10002   MARTELO  1500.0
7  10004     SERRA   200.0
8  10005   MACHADO   100.0
9  10003     PREGO    60.0

In [17]:
con.close()